CREATE TABLE IF NOT EXISTS categories (
id INTEGER PRIMARY KEY AUTOINCREMENT,
nom VARCHAR(20),
date DATE
);

CREATE TABLE IF NOT EXISTS exo3(
id INTEGER PRIMARY KEY AUTOINCREMENT,
distance SMALLINT ,
temperature  TINYINT, 
status BOOLEAN
);
