CREATE TABLE IF NOT EXISTS ville (
id INTEGER PRIMARY KEY AUTOINCREMENT,
nom VARCHAR (255) DEFAULT "inconnu",
distance SMALLINT DEFAULT 0,
dt_creation DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exo4(
id INTEGER PRIMARY KEY AUTOINCREMENT,
tva FLOAT DEFAULT 1.2,
prix FLOAT,
description TEXT,
dt_creation DATE DEFAULT "inconnu"
);